# Generated by Django 6.1.2 on 2026-10-07 19:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('computer', 'Computer'), ('online', 'Online')], max_length=10)),
                ('difficulty', models.CharField(blank=True, max_length=10)),
                ('board_size', models.PositiveSmallIntegerField(default=8)),
                ('board_state', models.JSONField()),
                ('current_color', models.CharField(default='black', max_length=5)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], max_length=12)),
                ('black_token', models.CharField(blank=True, max_length=64)),
                ('white_token', models.CharField(blank=True, max_length=64)),
                ('black_last_seen', models.DateTimeField(blank=True, null=True)),
                ('white_last_seen', models.DateTimeField(blank=True, null=True)),
                ('black_count', models.PositiveSmallIntegerField(default=2)),
                ('white_count', models.PositiveSmallIntegerField(default=2)),
                ('result', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('draw', 'Draw')], max_length=5)),
                ('end_reason', models.CharField(blank=True, choices=[('no_moves', 'No Moves'), ('forfeit', 'Forfeit'), ('disconnect', 'Disconnect')], max_length=10)),
                ('last_event', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='database.playerprofile')),
                ('white_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='database.playerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=5)),
                ('row', models.PositiveSmallIntegerField()),
                ('col', models.PositiveSmallIntegerField()),
                ('flipped_count', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='database.gamerecord')),
            ],
            options={
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('game', 'number'), name='unique_move_number')],
            },
        ),
    ]
